# Generated by Django 4.1.6 on 2023-02-03 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('full_info', models.TextField()),
                ('header_images', models.ImageField(blank=True, default='news.png', upload_to='')),
                ('date', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
