# Generated by Django 4.1.6 on 2023-02-10 07:11

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='new',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='category',
        ),
        migrations.AlterField(
            model_name='new',
            name='full_info',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='new',
            name='header_images',
            field=models.ImageField(blank=True, default='news/images/news.jpg', upload_to='news/images'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
            ],
        ),
        migrations.AddField(
            model_name='new',
            name='sub_category',
            field=models.ManyToManyField(blank=True, null=True, to='news.subcategory'),
        ),
    ]
