# Generated by Django 4.1.6 on 2023-02-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ManyToManyField(related_name='category', to='news.category'),
        ),
    ]
