# Generated by Django 4.1.7 on 2023-03-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
