# Generated by Django 4.1.6 on 2023-02-04 06:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_new_full_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='full_info',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
    ]
