# Generated by Django 4.1.6 on 2023-02-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='category',
            field=models.ManyToManyField(to='news.category'),
        ),
    ]
