# Generated by Django 4.1.7 on 2023-03-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_name_en_category_name_ru_category_name_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='view_home',
            field=models.BooleanField(default=True),
        ),
    ]
