# Generated by Django 4.1.7 on 2023-03-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_new_view_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='view_home',
        ),
        migrations.AddField(
            model_name='category',
            name='view_home',
            field=models.BooleanField(default=True),
        ),
    ]
